[package]
name = "webgl-fundamentals-1"
version = "0.1.0"
authors = ["Noumir.Poutipou <noumir.poutipou@bulange.fr>"]
edition = "2018"

[dependencies]
stdweb = "0.4.17"
stdweb-derive = "0.5.1"
serde = "1.0.91"
serde_derive = "1.0.91"

[build-dependencies]
webgl_generator = "0.2.0"
